version: '3'
services:
  postgres:
    image: postgres
    restart: always
    container_name: pg_container
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=book_db

    volumes:
      - gopgdata:/var/lib/postgresql/data

    networks:
      - go-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - gopgadmindata:/var/lib/pgadmin
    ports:
      - 8080:80
    networks:
      - go-network

networks:
  go-network:
    driver: bridge
volumes:
  gopgdata:
  gopgadmindata:
